[features]
seeds = false
[programs.devnet]
anchor_awesome = "2ihpd9SPDQk2EmT7WBdBoMMVcLwYfF5U4mbmf6TdBB4A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/petersun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
